import { useId } from "react";

/**
 * The athlete.
 *
 * Every exercise demo in the app is this figure, posed by the solver in
 * `src/anim`. It is drawn entirely in vector, so all 39 catalogue
 * movements plus anything the AI invents cost zero download.
 *
 * ── What changed, and why it matters ──────────────────────────────────
 *
 * The previous figure was built from `<path>` elements with a uniform
 * `stroke-width`: a limb was a rod of constant thickness with a round cap.
 * That is why it read as a toy. Real limbs are tapered and have mass — a
 * thigh is roughly twice as thick at the hip as at the knee, a calf bulges
 * behind the shin, a deltoid caps the shoulder. None of that can be
 * expressed by a stroke.
 *
 * Every segment is now a FILLED, TAPERED path generated by `limb()` below,
 * with a per-shape gradient giving it volume. The head came down from r16
 * to r13 — at r16 the figure was five heads tall, which is a child's
 * proportions and the single loudest "cheap illustration" tell in the old
 * artwork.
 *
 * ── What deliberately did NOT change ──────────────────────────────────
 *
 * Every joint coordinate, group class name and transform-origin is
 * byte-identical to before, because `src/anim/rig.ts` measures its segment
 * lengths off this file and the renderer resolves these exact class names
 * once per mount:
 *
 *   hip 180,112 · shoulder 180,68 · head 180,36
 *   knee 162.5/197.5,144.5 · foot 145/215,177
 *   elbow 156/204,81.5 · hand 132/228,95
 *
 *   leg = <g motion-leg-*  (hip pivot)>      thigh → <g motion-knee-*>  shin+shoe
 *   arm = <g motion-arm-*  (shoulder pivot)> upper → <g motion-elbow-*> forearm+hand
 *
 * So this is a re-skin, not a re-rig: every solved pose, the IK grounding
 * and the whole `anim-check` harness keep working untouched.
 *
 * ── One honest limitation ─────────────────────────────────────────────
 *
 * Both arms pivot from 180,68 — the centre of the chest — rather than from
 * two separate shoulder sockets, because that is the rig the solver was
 * built against. The torso is therefore drawn OVER the upper arms, which
 * hides the shared pivot. It also means the figure cannot show a shoulder
 * girdle that shrugs or protracts.
 */

export type FigureGender = "male" | "female" | "neutral";

/* ------------------------------------------------------------------ */
/*  Palette                                                            */
/* ------------------------------------------------------------------ */

const SKIN = { lit: "#f6cda5", base: "#e2a475", shade: "#b87c4e" };
const KIT = { lit: "#39415a", base: "#262d40", shade: "#161b28" };
const HAIR = "#241a15";
const SHOE = "#eef2f8";
const SHOE_SHADE = "#b9c2d1";

/** Kit trim. The only place the figure itself is gendered by colour —
 *  everything else is body shape, so the two read as the same athlete. */
const TRIM: Record<FigureGender, string> = {
  male: "#38d6ff",
  female: "#ff7ab8",
  neutral: "#00e5a0",
};

/* ------------------------------------------------------------------ */
/*  Tapered limb geometry                                              */
/* ------------------------------------------------------------------ */

/**
 * A filled limb segment from (x1,y1) to (x2,y2), `w1` wide at the start
 * and `w2` at the end, with `bulge` extra half-width at the midpoint for
 * the muscle belly (bicep, calf, quad sweep).
 *
 * Both ends are rounded with cubic curves rather than arcs. An `A` command
 * needs large-arc and sweep flags whose correct values depend on the
 * segment's direction, and these segments point in every direction as the
 * solver poses them — one wrong flag inverts a cap into a spike. Cubics
 * have no flags, so the same expression is correct at every angle.
 */
function limb(
  x1: number,
  y1: number,
  w1: number,
  x2: number,
  y2: number,
  w2: number,
  bulge = 0,
): string {
  const dx = x2 - x1;
  const dy = y2 - y1;
  const len = Math.hypot(dx, dy) || 1;
  const ux = dx / len;
  const uy = dy / len;
  // Left-hand perpendicular.
  const px = -uy;
  const py = ux;

  const r1 = w1 / 2;
  const r2 = w2 / 2;
  const rm = (r1 + r2) / 2 + bulge;
  const mx = (x1 + x2) / 2;
  const my = (y1 + y2) / 2;

  // Cap control-point reach. 4/3·tan(π/8)·r ≈ 0.552r per quadrant, so a
  // half-circle drawn as one cubic wants about 1.33r.
  const c1 = r1 * 1.33;
  const c2 = r2 * 1.33;

  const p = (x: number, y: number) => `${x.toFixed(2)} ${y.toFixed(2)}`;

  return [
    `M${p(x1 + px * r1, y1 + py * r1)}`,
    `Q${p(mx + px * rm, my + py * rm)} ${p(x2 + px * r2, y2 + py * r2)}`,
    `C${p(x2 + px * r2 + ux * c2, y2 + py * r2 + uy * c2)} ${p(x2 - px * r2 + ux * c2, y2 - py * r2 + uy * c2)} ${p(x2 - px * r2, y2 - py * r2)}`,
    `Q${p(mx - px * rm, my - py * rm)} ${p(x1 - px * r1, y1 - py * r1)}`,
    `C${p(x1 - px * r1 - ux * c1, y1 - py * r1 - uy * c1)} ${p(x1 + px * r1 - ux * c1, y1 + py * r1 - uy * c1)} ${p(x1 + px * r1, y1 + py * r1)}`,
    "Z",
  ].join(" ");
}

/* ------------------------------------------------------------------ */
/*  Per-gender build                                                   */
/* ------------------------------------------------------------------ */

interface Build {
  /**
   * Where the LEFT upper arm is drawn from (the right mirrors about
   * x=180). Deliberately not the pivot.
   *
   * Both arms pivot at 180,68 — the centre of the chest — because that is
   * the rig the solver was built against. Drawing the arm from that point
   * meant its outer edge stayed inside the torso silhouette until y≈79,
   * so the arm appeared to grow out of the ribs rather than the shoulder,
   * which is the single thing that made the whole figure read as wrong.
   * Drawing it from the shoulder instead puts the deltoid where a deltoid
   * goes, and the arm clears the body at y≈73.
   *
   * The cost is that this root orbits the pivot as the arm rotates — but
   * it is only ~11px from it, and the torso is drawn over the arms, so
   * the root is under the chest at every angle the solver produces.
   */
  armRoot: [number, number];
  /** Segment widths: [start, end, bulge]. */
  upperArm: [number, number, number];
  foreArm: [number, number, number];
  thigh: [number, number, number];
  shin: [number, number, number];
  /** Torso silhouette, shoulders → waist → hip. */
  torso: string;
  /** Kit shape, clipped to the torso. */
  kit: string;
  /** Lower edge of the kit, for the trim band. */
  trimY: number;
  /** Top of the pelvis block. The gap between this and `trimY` is the
   *  exposed midriff — without it the vest and the shorts meet and the
   *  figure reads as wearing a one-piece with a belt. */
  pelvisY: number;
  /** How far down the thigh the shorts reach. */
  shortsTo: number;
  shortsW: [number, number];
}

const MALE: Build = {
  armRoot: [169, 63],
  upperArm: [18, 13.5, 1.6],
  foreArm: [12.5, 9, 0.6],
  thigh: [25, 17, 1.6],
  shin: [17, 9.5, 2.2],
  // A flat neck base with a fast trapezius rise out to the shoulder, NOT a
  // curve from the neck straight to the widest point — that domes the top
  // of the chest and the whole figure reads as a barrel.
  torso:
    "M170 49 L190 49 C196 50 200 55 200.5 64 C201 73 197 81 195 90 C193.5 97 193.5 104 196.5 111 L197.5 117 L162.5 117 L163.5 111 C166.5 104 166.5 97 165 90 C163 81 159 73 159.5 64 C160 55 164 50 170 49 Z",
  // Scooped vest neckline, straps over the traps, hem above the navel.
  kit: "M152 44 L169 47 Q180 60 191 47 L208 44 L208 92 L152 92 Z",
  trimY: 92,
  pelvisY: 106,
  shortsTo: 133,
  shortsW: [26, 20],
};

const FEMALE: Build = {
  armRoot: [171, 64],
  upperArm: [15, 11, 1.2],
  foreArm: [10.5, 8, 0.5],
  thigh: [23.5, 15, 1.3],
  shin: [15, 8.5, 1.9],
  torso:
    "M172 50 L188 50 C192.5 51 196 56 197 64 C198 71 194 78 192 87 C190.5 92 190.5 97 193 103 C195.5 109 197 113 198 118 L162 118 C163 113 164.5 109 167 103 C169.5 97 169.5 92 168 87 C166 78 162 71 163 64 C164 56 167.5 51 172 50 Z",
  kit: "M154 46 L169 51 Q180 62 191 51 L206 46 L206 79 Q180 85 154 79 Z",
  trimY: 79,
  pelvisY: 104,
  shortsTo: 136,
  shortsW: [24, 18],
};

const NEUTRAL: Build = {
  armRoot: [170, 63.5],
  upperArm: [15.5, 12, 1.2],
  foreArm: [11.5, 8.5, 0.5],
  thigh: [24, 16, 1.4],
  shin: [16, 9, 2],
  torso:
    "M171 49 L189 49 C195 50 199 55 199.5 64 C200 72 196 80 194 89 C192.5 96 192.5 103 195.5 110 L196.5 117 L163.5 117 L164.5 110 C167.5 103 167.5 96 166 89 C164 80 160 72 160.5 64 C161 55 165 50 171 49 Z",
  kit: "M153 45 L169 49 Q180 61 191 49 L207 45 L207 87 L153 87 Z",
  trimY: 87,
  pelvisY: 105,
  shortsTo: 134,
  shortsW: [25, 19],
};

function buildFor(gender: FigureGender): Build {
  return gender === "female" ? FEMALE : gender === "male" ? MALE : NEUTRAL;
}

/* ------------------------------------------------------------------ */
/*  Parts                                                              */
/* ------------------------------------------------------------------ */

function Hair({ gender }: { gender: FigureGender }) {
  if (gender === "female") {
    return (
      <>
        <path
          d="M166.5 30 Q165 19 173 16 Q180 13.5 187 16 Q195 19 193.5 30 Q194.5 40 192.5 48 Q190.5 39 187 35.5 Q189 27 180 25.2 Q171 27 173 35.5 Q169.5 39 167.5 48 Q165.5 40 166.5 30 Z"
          fill={HAIR}
        />
        {/* Ponytail. Sits behind the head so a rotated pose never shows it
            clipping across the face. */}
        <path d="M191 31 Q203 36 200 50 Q197 42 189 38 Z" fill={HAIR} />
      </>
    );
  }
  if (gender === "male") {
    // A crop that actually covers the skull. The previous hair was a thin
    // rim across the crown, which left the head reading as bald with a
    // seam drawn on it.
    return (
      <path
        d="M167.4 32 Q166 22 173 18.5 Q180 15.5 187 18.5 Q194 22 192.6 32 Q191 27 186 25.5 Q180 24 174 25.5 Q169 27 167.4 32 Z"
        fill={HAIR}
      />
    );
  }
  return (
    <path
      d="M168 31 Q167 22 173.5 19 Q180 16.5 186.5 19 Q193 22 192 31 Q190 26.5 185.5 25.2 Q180 23.8 174.5 25.2 Q170 26.5 168 31 Z"
      fill={HAIR}
    />
  );
}

/** Front-view trainer. Authored at the ankle with the toe toward −x, then
 *  mirrored for the other foot, so both shoes splay outward. */
function Shoe({ x, dir, trim }: { x: number; dir: 1 | -1; trim: string }) {
  return (
    <g transform={`translate(${x} 177) scale(${dir} 1)`}>
      <path
        d="M-10.5 -3.5 Q-13 1 -12.5 5.5 Q-12 8.5 -8 8.5 L6 8.5 Q10 8.5 10 5 Q10 0.5 6.5 -2 Q2.5 -5 -2 -5 Q-7 -5 -10.5 -3.5 Z"
        fill={SHOE}
      />
      <path d="M-12.6 4 Q-12 8.5 -8 8.5 L6 8.5 Q10 8.5 10 5 Z" fill={trim} />
      <path d="M-4 -4.6 Q-1 0 1.5 5" stroke={SHOE_SHADE} strokeWidth={1.2} fill="none" strokeLinecap="round" />
    </g>
  );
}

/** A hand, not a circle. Slight taper into a mitt with a thumb notch. */
function Hand({ x, y, dir, fill }: { x: number; y: number; dir: 1 | -1; fill: string }) {
  return (
    <g transform={`translate(${x} ${y}) scale(${dir} 1) rotate(28)`}>
      <path
        d="M-4.5 -5.5 Q3 -6.5 6 -1.5 Q8.5 2.5 5.5 6 Q2 9.5 -2.5 8 Q-6.5 6.5 -7 1.5 Q-7.3 -3.5 -4.5 -5.5 Z"
        fill={fill}
      />
      <path d="M-6.5 -1.5 Q-9.5 0.5 -8 3.5" stroke={fill} strokeWidth={3.4} fill="none" strokeLinecap="round" />
    </g>
  );
}

/* ------------------------------------------------------------------ */

export default function HumanFigure({ gender = "male" }: { gender?: FigureGender }) {
  // `useId` is unique per component instance, which is what keeps a grid of
  // forty figures from all resolving `url(#skin)` to the first one's
  // gradient. The colons React puts in the id are not valid in a URL
  // fragment, hence the strip.
  const uid = useId().replace(/[^a-zA-Z0-9]/g, "");
  const gSkin = `sk${uid}`;
  const gKit = `kt${uid}`;
  const gTorso = `ts${uid}`;
  const clip = `tc${uid}`;

  const b = buildFor(gender);
  const trim = TRIM[gender];
  const skin = `url(#${gSkin})`;
  const kitFill = `url(#${gKit})`;

  const KNEE_L = { x: 162.5, y: 144.5 };
  const KNEE_R = { x: 197.5, y: 144.5 };
  const ELBOW_L = { x: 156, y: 81.5 };
  const ELBOW_R = { x: 204, y: 81.5 };

  return (
    <>
      <defs>
        {/* Across-the-body shading in each shape's own box, so every limb
            gets its own light side without a single global gradient that
            would break the moment a limb rotated. */}
        <linearGradient id={gSkin} x1="0" y1="0" x2="1" y2="0.4">
          <stop offset="0%" stopColor={SKIN.lit} />
          <stop offset="46%" stopColor={SKIN.base} />
          <stop offset="100%" stopColor={SKIN.shade} />
        </linearGradient>
        <linearGradient id={gKit} x1="0" y1="0" x2="1" y2="0.4">
          <stop offset="0%" stopColor={KIT.lit} />
          <stop offset="52%" stopColor={KIT.base} />
          <stop offset="100%" stopColor={KIT.shade} />
        </linearGradient>
        <linearGradient id={gTorso} x1="0.1" y1="0" x2="0.95" y2="0.6">
          <stop offset="0%" stopColor={SKIN.lit} />
          <stop offset="40%" stopColor={SKIN.base} />
          <stop offset="100%" stopColor={SKIN.shade} />
        </linearGradient>
        <clipPath id={clip}>
          <path d={b.torso} />
        </clipPath>
      </defs>

      {/* ---------------- Legs ---------------- */}
      {/* Drawn first so the pelvis and torso overlap them at the hip. */}
      <g className="motion-leg-l" style={{ transformOrigin: "180px 112px" }}>
        <path d={limb(180, 112, b.shortsW[0], 171, b.shortsTo, b.shortsW[1])} fill={kitFill} />
        <path
          d={limb(171, b.shortsTo - 4, b.thigh[0] * 0.78, KNEE_L.x, KNEE_L.y, b.thigh[1], b.thigh[2])}
          fill={skin}
        />
        <g className="motion-knee-l" style={{ transformOrigin: `${KNEE_L.x}px ${KNEE_L.y}px` }}>
          <path d={limb(KNEE_L.x, KNEE_L.y, b.shin[0], 145, 174, b.shin[1], b.shin[2])} fill={skin} />
          <Shoe x={145} dir={-1} trim={trim} />
        </g>
      </g>

      <g className="motion-leg-r" style={{ transformOrigin: "180px 112px" }}>
        <path d={limb(180, 112, b.shortsW[0], 189, b.shortsTo, b.shortsW[1])} fill={kitFill} />
        <path
          d={limb(189, b.shortsTo - 4, b.thigh[0] * 0.78, KNEE_R.x, KNEE_R.y, b.thigh[1], b.thigh[2])}
          fill={skin}
        />
        <g className="motion-knee-r" style={{ transformOrigin: `${KNEE_R.x}px ${KNEE_R.y}px` }}>
          <path d={limb(KNEE_R.x, KNEE_R.y, b.shin[0], 215, 174, b.shin[1], b.shin[2])} fill={skin} />
          <Shoe x={215} dir={1} trim={trim} />
        </g>
      </g>

      {/* ---------------- Upper body ----------------
          Arms, torso and head share the hip pivot so a push-up, plank or
          dip tilts them as one rigid piece. Rotating the torso on its own
          pivot leaves the head hanging where the shoulders used to be. */}
      <g className="motion-upper-body" style={{ transformOrigin: "180px 112px" }}>
        <g className="motion-arm-l" style={{ transformOrigin: "180px 68px" }}>
          <path
            d={limb(b.armRoot[0], b.armRoot[1], b.upperArm[0], ELBOW_L.x, ELBOW_L.y, b.upperArm[1], b.upperArm[2])}
            fill={skin}
          />
          <g className="motion-elbow-l" style={{ transformOrigin: `${ELBOW_L.x}px ${ELBOW_L.y}px` }}>
            <path
              d={limb(ELBOW_L.x, ELBOW_L.y, b.foreArm[0], 133, 94, b.foreArm[1], b.foreArm[2])}
              fill={skin}
            />
            <Hand x={132} y={95} dir={-1} fill={SKIN.base} />
          </g>
        </g>

        <g className="motion-arm-r" style={{ transformOrigin: "180px 68px" }}>
          <path
            d={limb(360 - b.armRoot[0], b.armRoot[1], b.upperArm[0], ELBOW_R.x, ELBOW_R.y, b.upperArm[1], b.upperArm[2])}
            fill={skin}
          />
          <g className="motion-elbow-r" style={{ transformOrigin: `${ELBOW_R.x}px ${ELBOW_R.y}px` }}>
            <path
              d={limb(ELBOW_R.x, ELBOW_R.y, b.foreArm[0], 227, 94, b.foreArm[1], b.foreArm[2])}
              fill={skin}
            />
            <Hand x={228} y={95} dir={1} fill={SKIN.base} />
          </g>
        </g>

        {/* Neck. Sits under the torso so the trapezius edge covers its base. */}
        <path d={limb(180, 44, 15, 180, 60, 17)} fill={SKIN.shade} />

        <g className="motion-torso">
          <path d={b.torso} fill={`url(#${gTorso})`} />

          <g clipPath={`url(#${clip})`}>
            <path d={b.kit} fill={kitFill} />

            {/* Pelvis block. Without it the two hip-anchored shorts shapes
                leave a visible notch at the crotch the moment a movement
                spreads the legs — jacks, sumo squats, skater hops. */}
            <rect x={146} y={b.pelvisY} width={68} height={20} fill={kitFill} />

            {/* The one accent on the body, and it sits on the waistband
                where a waistband actually is. An earlier version put it at
                the vest hem, which read as a belt worn across the chest. */}
            <rect x={146} y={b.pelvisY} width={68} height={2.5} fill={trim} opacity={0.85} />

            {/* Linea alba, in the exposed midriff only. Faint on purpose:
                at a 44px thumbnail anything stronger reads as a scar. */}
            <path
              d={`M180 ${b.trimY + 3} L180 ${b.pelvisY - 2}`}
              stroke={SKIN.shade}
              strokeWidth={1.1}
              strokeLinecap="round"
              fill="none"
              opacity={0.38}
            />

            {/* Core shadow down both flanks. Neutral black rather than a
                skin tone, because it has to sit over the kit as well. */}
            <g fill="#000" opacity={0.2}>
              <path d="M155 60 Q161 86 163 118 L153 118 L153 60 Z" />
              <path d="M205 60 Q199 86 197 118 L207 118 L207 60 Z" />
            </g>
          </g>

          {/* Silhouette edge. One hairline holds the body together against
              the dark card without reading as a line drawing. */}
          <path d={b.torso} fill="none" stroke={SKIN.shade} strokeWidth={1.1} opacity={0.45} />
        </g>

        <g className="motion-head">
          <circle cx={180} cy={36} r={13} fill={skin} />
          {/* Ear, on the shaded side only — two ears on a front-facing head
              at this scale read as lumps. */}
          <ellipse cx={192.5} cy={37} rx={2.6} ry={3.6} fill={SKIN.shade} opacity={0.75} />
          <Hair gender={gender} />
          <circle cx={180} cy={36} r={13} fill="none" stroke={SKIN.shade} strokeWidth={1.1} opacity={0.5} />
        </g>
      </g>
    </>
  );
}
